config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :users, only:[:show, :destroy] 

  get "/" => "tasks#index"
  get "tasks/index" => "tasks#index"
  root :to =>  "tasks#index"
  get "tasks/new" => "tasks#new"
  post "tasks/create" => "tasks#create"
  get "tasks/show/:id" => "tasks#show", as: 'tasks_show_id' #asでprefix名（tasks_show_id）をつけている。
  get "tasks/edit/:id" => "tasks#edit"
  post "tasks/update/:id" => "tasks#update"
  delete "tasks/:id" => "tasks#destroy"
  


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, :detail, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :configure_account_update_parameters, if: :devise_controller? #編集機能について

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

    #編集機能について
    def configure_account_update_parameters
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end

  #新規登録・ログインした後のページへのパス
  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
    #ログアウトした時のパスをログイン画面にするように設定。
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, except: [:new]
  # ログインしていない場合、ログイン画面に移動する
  before_action :correct_task,only: [:show, :edit, :update]
  # # URLに直打ちした時にトップページやログイン画面へ移動する。
  
  def index
    @tasks = Task.where(user_id: current_user.id)
    # トップページに表示するタスクを自分のタスクのみに設定
  end

  def new
    @task = Task.new
  end
  
  def create
    @task = Task.new(title: params[:title], detail: params[:detail])
    @task.user_id = current_user.id
      if @task.save
        flash[:notice] = "タスク作成に成功しました"
        redirect_to "/"
      else
        flash[:error] = @task.errors.full_messages
        render :new, status: :unprocessable_entity
        #HTTPのレスポンスステータスコードを422（Unprocessable Entity）に設定するオプションです。
        #これは、リクエストがバリデーションエラーやクライアント側の問題などの理由で処理できない場合を示します。
      end
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find_by(id: params[:id])
  end


  def update
    @task = Task.find_by(id: params[:id])
    @task.title = params[:title]
    @task.detail = params[:detail]

    if @task.save
      flash[:notice] = "タスク更新に成功しました"
      redirect_to "/"
    else
      flash[:error] = @task.errors.full_messages
      redirect_to "/tasks/edit/#{@task.id}"
      #画面遷移した時に初期値（前の入力内容）を入れておきたいので、redirect_toで画面遷移している。
    end    
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    flash[:notice] = "タスク削除に成功しました"
    redirect_to "/"
  end


  private

  def correct_task
    @task = Task.find_by(id:params[:id])
    if @task.user_id != current_user.id
      redirect_to new_user_session_path
      # @taskとログインユーザーidが異なっていたら、ログイン画面へ移動
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks.page(params[:page]).per(5).reverse_order
  end

  def destroy
    user = User.find(params[:id])
    binding.b
    if user.id == current_user.id && user.destroy
      flash[:notice] = "アカウント削除に成功しました"
      redirect_to new_user_registration_path
    else
      flash[:notice] = "無効な操作です。アカウント削除はできません。"
      redirect_to user_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <div class="body">
      <% if user_signed_in? %>
        <header>
          <div class="header-top">
            <div class="header-task">
              <div><%= link_to root_path do %><img src="/assets/header.png" alt="logo" id="logo" width="100" height="100"><% end %></div>
              <div><%= link_to "投稿一覧", root_path, class: "text-white" %></div>
              <div><%= link_to "新規投稿", tasks_new_path, class: "text-white" %></div>
            </div>
            <div class="header-user">
              <%= current_user.name %>
              <div><%= link_to "マイページ詳細", user_path(current_user.id), class: "text-white" %></div>
              <div><%= link_to "マイページ編集", edit_user_registration_path(current_user.id), class: "text-white" %></div> 
              <div><%= button_to "ログアウト", destroy_user_session_path, method: :delete, class: "text-white" %></div>
              <div><%= button_to "アカウント削除", user_path(current_user.id), method: :delete, data: { turbo_confirm: "本当に削除しますか?" }, class: "text-white" %></div>
            </div>
          </div>
        </header>
      <% end %> 

      <div class="main">
        <% flash.each do |key, value| %>
            <p class="alert alert-<%= key %>">
              <%= value %>
            </p>
        <% end %>

        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= link_to "トップページ", root_path %>
<%= link_to "新規投稿", tasks_new_path %>

<h3>編集</h3>


<%= form_with url: "/tasks/update/#{@task.id}" do |f| %>
  <p>タイトル</p>
  <%= f.text_field :title, value: @task.title %></br>

  <p>詳細</p>
  <textarea name="detail" cols="50" rows="10"><%= @task.detail %></textarea>
  <%# @task.detailで初期値を入れいている %>
  <%# nameにdetailを設定することで、更新する内容をパラメーターとして渡すようにしている %>
  <%#<%= f.text_area :detail, size: "50x10" %></br>
  <%= f.submit '更新' %>
  <%= link_to "削除", "/tasks/#{@task.id}", data: { turbo_method: :delete } %>
<% end %>

app/views/tasks/index.html.erb
<h1>Todoapp</h1>

<% @tasks.each do |task| %>
  <li>
    <%= link_to "#{task.title}", tasks_show_id_path(task) %><br>
    <%= link_to "詳細", tasks_show_id_path(task) %>
    <%# 上２つのリンクはどちらも詳細ページへリンクするようにしている %>
    <%= link_to "編集", "/tasks/edit/#{task.id}" %>
    <%= link_to "削除", "/tasks/#{task.id}", data: { turbo_method: :delete } %>
  </li>
<% end %>

app/views/tasks/new.html.erb
<%= link_to "トップページ", root_path %>

<h2>新規投稿</h2>

<%= form_with url: tasks_create_path do |f| %>
  <p>タイトル</p>
  <%= f.text_field :title %></br>

  <p>詳細</p>
  <%= f.text_area :detail, size: "50x10" %></br>
  <%= f.submit '保存'%>
<% end %>

app/views/tasks/show.html.erb
<%= link_to "トップページ", root_path %>
<%= link_to "新規投稿", tasks_new_path %>

<h3>タスク詳細</h3>

<p>タイトル</p>
<%= @task.title %><br>

<p>詳細</p>
<%= @task.detail %><br>
<%= link_to "編集", "/tasks/edit/#{@task.id}" %>
<%= link_to "削除", "/tasks/#{@task.id}", data: { turbo_method: :delete } %>

app/views/users/show.html.erb
  <% if user_signed_in? && @user == current_user %>
    <h1>マイページ詳細</h1>
  <% end %>

  <% @tasks.each do |task| %>
    <%= link_to "#{task.title}", tasks_show_id_path(task) %><br>
  <% end %>

  <%= paginate @tasks %> 